FROM mariadb:10.3

ENV TZ=Asia/Tokyo \
    MYSQL_DATABASE=laradiy-db \
    MYSQL_USER=laradiy-user \
    MYSQL_PASSWORD=laradiy-password \
    MYSQL_ROOT_PASSWORD=laradiy-password

COPY ./my.cnf /etc/my.cnf